env:
  global:
    - secure: Dr8zLzyRCYquYoKp9Yc8c8LZabfHJue94YSI3A7lGXuZF0w1IKwhyX3QldeJv+K2jHr1akgNnFtobK6dp4Nud9qsp5gLZkwJmtJ+U9vgdGXaByKH7VmVu7SZhi4b+omC6/V+NR4N29lUfg6G7u/XSKvqyog485SOguY0BiKARJ4=

install:
  # rustc
  - wget http://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - tar xzf rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - export PATH=$PATH:$(pwd)/rust-nightly-x86_64-unknown-linux-gnu/bin
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/rust-nightly-x86_64-unknown-linux-gnu/lib
  # liblua
  - sudo apt-get install liblua5.2-dev
  # cargo
  - curl -O http://static.rust-lang.org/cargo-dist/cargo-nightly-linux.tar.gz
  - tar xf cargo-nightly-linux.tar.gz
  - export PATH=$PATH:$(pwd)/cargo-nightly/bin

script:
  - cd rust-hl-lua
  - cargo test
  - cd ../rust-hl-lua-modules
  - cargo test
  - cd ..
  - rustdoc rust-hl-lua/src/lib.rs

after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
