language: rust

install:
  - sudo apt-get install liblua5.2-dev

script:
  - cargo test --manifest-path lua52-sys/Cargo.toml
  - cargo test --manifest-path hlua/Cargo.toml
  #- cargo test --manifest-path rust-hl-lua-modules/Cargo.toml
