[package]
name = "lua52-sys"
version = "0.2.0"
authors = ["wildbook <book.wille@gmail.com>"]
description = "Bindings for Lua 5.2"
edition = "2018"
build = "build.rs"
links = "lua52"
license = "MIT"

[build-dependencies]
pkg-config = "0.3"
cc = "1.0"

[dependencies]
libc = "0.2"
